// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_Klintyk.Models;

namespace Mission6_Klintyk.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6_Klintyk.Models.CategoryResponse", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Thriller"
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Romance"
                        },
                        new
                        {
                            CategoryId = 5,
                            Category = "Western"
                        });
                });

            modelBuilder.Entity("Mission6_Klintyk.Models.Movie", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FilmID = 1,
                            CategoryId = 1,
                            Director = "Ryan Coogler",
                            Edited = false,
                            Lent_to = "Oliva Olred",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Black Panther",
                            Year = 2018
                        },
                        new
                        {
                            FilmID = 2,
                            CategoryId = 2,
                            Director = "Frank Coraci",
                            Edited = true,
                            Lent_to = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Blended",
                            Year = 2014
                        },
                        new
                        {
                            FilmID = 3,
                            CategoryId = 1,
                            Director = "David Dobkin",
                            Edited = false,
                            Lent_to = "Carter Jenses",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Shanghai Knights",
                            Year = 2003
                        },
                        new
                        {
                            FilmID = 4,
                            CategoryId = 5,
                            Director = "Alejandro G.Iñárritu",
                            Edited = false,
                            Lent_to = "",
                            Notes = "",
                            Rating = "R",
                            Title = "The Revnant",
                            Year = 2015
                        });
                });

            modelBuilder.Entity("Mission6_Klintyk.Models.Movie", b =>
                {
                    b.HasOne("Mission6_Klintyk.Models.CategoryResponse", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
